import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

export interface PortalTypeInfo {
  /** '' sentinel for a portal-less setup. */
  name: string
  /** UNQUALIFIED policy names. */
  policyNames: string[]
}

/**
 * Writes rbac.d.ts augmenting the RbacTypes interface. Every interpolated
 * name — union literals AND property keys — goes through JSON.stringify so
 * user-controlled policy/portal names can never inject declaration code
 * (v0 interpolated them raw).
 */
export async function generateTypes(portals: PortalTypeInfo[], output: string): Promise<void> {
  const outputPath = resolve(output)
  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, renderDeclaration(portals), 'utf8')
}

function renderDeclaration(portals: PortalTypeInfo[]): string {
  const portalUnion = union(portals.map(portal => portal.name))
  const allPolicies = union(portals.flatMap(portal => portal.policyNames))

  const portalPolicies =
    portals.length === 0
      ? 'Record<string, string>'
      : `{\n${portals
          .map(portal => `      ${JSON.stringify(portal.name)}: ${union(portal.policyNames)}`)
          .join('\n')}\n    }`

  return [
    '// Generated by `rbac sync` / `rbac generate` — do not edit.',
    '',
    // `export {}` makes this file a module so `declare module` below is an
    // AUGMENTATION of '@kyrobit/rbac', not an ambient module that replaces it.
    'export {}',
    '',
    "declare module '@kyrobit/rbac' {",
    '  interface RbacTypes {',
    `    Portal: ${portalUnion}`,
    `    PolicyName: ${allPolicies}`,
    `    PortalPolicies: ${portalPolicies}`,
    '  }',
    '}',
    '',
  ].join('\n')
}

function union(names: string[]): string {
  const unique = [...new Set(names)].sort()
  if (unique.length === 0) return 'string'
  return unique.map(name => JSON.stringify(name)).join(' | ')
}
