import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

export interface DomainTypeInfo {
  /** '' sentinel for a setup with no domains. */
  name: string
  /** UNQUALIFIED policy names. */
  policyNames: string[]
}

/**
 * Writes kyroguard.d.ts augmenting the RbacTypes interface. Every interpolated
 * name — union literals AND property keys — goes through JSON.stringify so
 * user-controlled policy/domain names can never inject declaration code.
 */
export async function generateTypes(domains: DomainTypeInfo[], output: string): Promise<void> {
  const outputPath = resolve(output)
  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, renderDeclaration(domains), 'utf8')
}

function renderDeclaration(domains: DomainTypeInfo[]): string {
  const domainUnion = union(domains.map(domain => domain.name))
  const allPolicies = union(domains.flatMap(domain => domain.policyNames))

  const domainPolicies =
    domains.length === 0
      ? 'Record<string, string>'
      : `{\n${domains
          .map(domain => `      ${JSON.stringify(domain.name)}: ${union(domain.policyNames)}`)
          .join('\n')}\n    }`

  return [
    '// Generated by `kyroguard sync` / `kyroguard generate` — do not edit.',
    '',
    // `export {}` makes this file a module so `declare module` below is an
    // AUGMENTATION of '@kyrobit/kyroguard', not an ambient module that replaces it.
    'export {}',
    '',
    "declare module '@kyrobit/kyroguard' {",
    '  interface RbacTypes {',
    `    Domain: ${domainUnion}`,
    `    PolicyName: ${allPolicies}`,
    `    DomainPolicies: ${domainPolicies}`,
    '  }',
    '}',
    '',
  ].join('\n')
}

function union(names: string[]): string {
  const unique = [...new Set(names)].sort()
  if (unique.length === 0) return 'string'
  return unique.map(name => JSON.stringify(name)).join(' | ')
}
